# Generated by Django 3.2.9 on 2021-11-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_comment_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_pic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
