# Generated by Django 3.2.9 on 2021-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_ticket_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_pic',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
