# Generated by Django 3.2.9 on 2021-11-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20211108_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='commentaire',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='titre',
        ),
    ]
