# Generated by Django 3.2.9 on 2021-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20211108_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='suit',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=None),
        ),
    ]
