# Generated by Django 3.2.9 on 2021-11-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_comment_suit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='suit',
        ),
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.IntegerField(choices=[('0', '- 0'), ('1', '- 1'), ('2', '- 2'), ('3', '- 3'), ('4', '- 4'), ('5', '- 5')], default=None),
        ),
    ]
