# Generated by Django 3.2.9 on 2021-11-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20211112_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
