# Generated by Django 3.2.9 on 2021-11-12 06:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0015_alter_comment_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='TicketReview',
        ),
    ]
