# Generated by Django 3.2.9 on 2021-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_userfollows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, '- 0'), (1, '- 1'), (2, '- 2'), (3, '- 3'), (4, '- 4'), (5, '- 5')]),
        ),
    ]
