# Generated by Django 3.2.9 on 2021-11-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_ticketreview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketreview',
            old_name='rating',
            new_name='rate',
        ),
    ]
