# Generated by Django 3.2.9 on 2021-11-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_alter_ticketreview_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
