# Generated by Django 3.2.9 on 2021-11-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_delete_userfollows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreview',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='tickets.ticket'),
        ),
    ]
