# Generated by Django 3.2.9 on 2021-11-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_alter_ticketreview_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketreview',
            options={'ordering': ['-time_created']},
        ),
    ]
