# Generated by Django 3.2.9 on 2021-11-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_alter_ticketreview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketreview',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Review-s'},
        ),
    ]
