# Generated by Django 3.2.9 on 2021-11-14 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_auto_20211114_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreview',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.ticket'),
        ),
    ]
