# Generated by Django 3.2.9 on 2021-11-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_ticketreview_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketreview',
            old_name='author',
            new_name='user',
        ),
    ]
