# Generated by Django 3.2.9 on 2021-11-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_auto_20211116_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='author',
        ),
    ]
