# Generated by Django 3.2.9 on 2021-11-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_auto_20211116_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name_plural': 'UserFollows'},
        ),
    ]
