# Generated by Django 3.2.9 on 2021-11-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_alter_review_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-date']},
        ),
    ]
