# Generated by Django 3.2.9 on 2021-11-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0042_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
