# Generated by Django 3.2.9 on 2021-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_delete_userfollows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
