# Generated by Django 3.2.9 on 2021-11-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_auto_20211119_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='time_created',
            new_name='created',
        ),
        migrations.AddField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
