# Generated by Django 3.2.9 on 2021-11-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_alter_review_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='author',
        ),
    ]
