# Generated by Django 3.2.9 on 2021-11-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0047_rename_user_ticket_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
    ]
