# Generated by Django 3.2.9 on 2021-12-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0068_alter_ticket_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created', 'author']},
        ),
    ]
