# Generated by Django 3.2.9 on 2021-12-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0069_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created', 'title']},
        ),
    ]
